#!/usr/bin/env bash

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 pipeline_name parser_name" >&2
  exit 1
fi

pipeline=$1
parser=$2

template_dir=$(cs-get-template-dir)
parse_dir=$pipeline/parse

mkdir -p $parse_dir/chains
mkdir -p $parse_dir/stellar
mkdir -p $parse_dir/patterns
mkdir -p $parse_dir/samples
mkdir -p $parse_dir/$parser
sed -e s/PARSER_NAME/$parser/g -e s/PIPELINE/$pipeline/g $template_dir/parse/parser.properties.template > $pipeline/parse/$parser/parser.properties.template
cp $template_dir/parse/chain-topic-map.json $parse_dir/$parser
