#!/usr/bin/env bash

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 pipeline_name profile_name" >&2
  exit 1
fi

pipeline=$1
profile_name=$2
profile_dir=$pipeline/profile/$profile_name

if [ -e "$profile_dir" ]; then
  echo "ERROR: $0 Profile $profile_name exists already." >&2
  exit 1
fi

template_dir=$(cs-get-template-dir)
mkdir -p $profile_dir
for FILE in $template_dir/profile/*; do
    sed -e s/PIPELINE/$pipeline/g  -e s/PROFILE_NAME/$profile_name/g $FILE > $profile_dir/${FILE##*/}
done
mkdir -p $profile_dir/rules
