#!/usr/bin/env bash

#
# Copyright 2020 - 2022 Cloudera. All Rights Reserved.
#
# This file is licensed under the Apache License Version 2.0 (the "License"). You may not use this file
# except in compliance with the License. You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0.
#
# This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. Refer to the License for the specific permissions and
# limitations governing your use of the file.
#

# Determine the location of the script to locate parcel
# Reference: http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
SOURCE="${BASH_SOURCE[0]}"
BIN_DIR="$(dirname "$SOURCE")"
while [ -h "$SOURCE" ]
do
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  BIN_DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done
BIN_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# Populate necessary environment variables
source $BIN_DIR/env_template.sh

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 pipeline_name parser_name" >&2
  exit 1
fi

pipeline=$1
parser=$2

parse_dir=$pipeline/parse

mkdir -p $parse_dir/chains
mkdir -p $parse_dir/stellar
mkdir -p $parse_dir/patterns
mkdir -p $parse_dir/samples
mkdir -p $parse_dir/$parser
sed -e s/PARSER_NAME/$parser/g -e s/PIPELINE/$pipeline/g $TEMPLATES_DIR/parse/parser.properties.template > $pipeline/parse/$parser/parser.properties.template
cp $TEMPLATES_DIR/parse/chain-topic-map.json $parse_dir/$parser
