#!/usr/bin/env bash

#
# Copyright 2020 - 2022 Cloudera. All Rights Reserved.
#
# This file is licensed under the Apache License Version 2.0 (the "License"). You may not use this file
# except in compliance with the License. You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0.
#
# This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. Refer to the License for the specific permissions and
# limitations governing your use of the file.
#

SOURCE="${BASH_SOURCE[0]}"
BIN_DIR="$(dirname "$SOURCE")"
while [ -h "$SOURCE" ]
do
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  BIN_DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done
BIN_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
source $BIN_DIR/env.sh


if [ "$#" -ne 2 ]; then
  echo "Usage: $0 pipeline_name enrichment_type" >&2
  exit 1
fi

pipeline=$1
enrichment_type=$2

triage_dir=$pipeline/triage

if [ ! -d "$triage_dir" ]; then
  echo "ERROR: $0 Pipeline $pipeline does not exist" >&2
  exit 1
fi

sed -e s/ENRICHMENT_TYPE/$enrichment_type/g -e s/PIPELINE/$pipeline/g $TEMPLATES_DIR/triage/load.properties.template > $pipeline/triage/load_${enrichment_type}.properties.template
