#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 pipeline_name " >&2
  exit 1
fi

pipeline=$1
index_dir=$pipeline/index
template_dir=$(cs-get-template-dir)

mkdir -p $index_dir
for FILE in $template_dir/index/*; do
    sed -e s/PIPELINE/$pipeline/g $FILE > $index_dir/${FILE##*/}
done
