#!/usr/bin/env bash

#
# Copyright 2020 - 2022 Cloudera. All Rights Reserved.
#
# This file is licensed under the Apache License Version 2.0 (the "License"). You may not use this file
# except in compliance with the License. You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0.
#
# This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. Refer to the License for the specific permissions and
# limitations governing your use of the file.
#

SOURCE="${BASH_SOURCE[0]}"
BIN_DIR="$(dirname "$SOURCE")"
while [ -h "$SOURCE" ]
do
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  BIN_DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done
BIN_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
source $BIN_DIR/env_template.sh

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 pipeline_name generator_name" >&2
  exit 1
fi

pipeline=$1
generator=$2

if [ ! -d "$pipeline" ]; then
  echo "ERROR: $0 Pipeline $pipeline does not exist" >&2
  exit 1
fi

generate_dir=$pipeline/generate

mkdir -p $generate_dir/$generator
sed -e s/GENERATOR_NAME/$generator/g -e s/PIPELINE/$pipeline/g $TEMPLATES_DIR/generate/generator.properties.template > $pipeline/generate/$generator/generator.properties.template
sed -e s/GENERATOR_NAME/$generator/g -e s/PIPELINE/$pipeline/g $TEMPLATES_DIR/generate/config.json > $pipeline/generate/$generator/config.json
cp -r $TEMPLATES_DIR/generate/templates $generate_dir/$generator
