#!/usr/bin/env bash
#
# Copyright 2020 - 2022 Cloudera. All Rights Reserved.
#
# This file is licensed under the Apache License Version 2.0 (the "License"). You may not use this file
# except in compliance with the License. You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0.
#
# This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. Refer to the License for the specific permissions and
# limitations governing your use of the file.
#

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 job_name" >&2
  exit 1
fi

job_name=$1

job_id=$(flink list 2>&1 | grep "${job_name}" | awk '{print $4}')

if [ -z "$job_id" ]; then
   echo "No job named $job_name."
else
   flink cancel $job_id 2>&1 | grep Cancelled
fi

