#!/usr/bin/env bash
if [ "$#" -ne 1 ]; then
  echo "Usage: $0 job_name" >&2
  exit 1
fi

job_name=$1

job_id=$(flink list 2>&1 | grep "${job_name}" | awk '{print $4}')

if [ -z "$job_id" ]; then
   echo "No job named $job_name."
else
   flink cancel $job_id 2>&1 | grep Cancelled
fi

