#!/usr/bin/env bash

#
# Copyright 2020 - 2022 Cloudera. All Rights Reserved.
#
# This file is licensed under the Apache License Version 2.0 (the "License"). You may not use this file
# except in compliance with the License. You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0.
#
# This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. Refer to the License for the specific permissions and
# limitations governing your use of the file.
#

script_dir=${BASH_SOURCE[0]}
while [ -L "$script_dir" ]; do # follow symbolic links 
  DIR=$( cd -P "$( dirname "$script_dir" )" >/dev/null 2>&1 && pwd )
  script_dir=$(readlink "$script_dir")
  [[ $script_dir != /* ]] && script_dir=$DIR/$script_dir # handle relative symbolic links
done
script_dir=$( cd -P "$( dirname "$script_dir" )" >/dev/null 2>&1 && pwd )
echo $(dirname "$script_dir/../etc/conf/templates")/templates

