#!/usr/bin/env bash

#
# Copyright 2020 - 2022 Cloudera. All Rights Reserved.
#
# This file is licensed under the Apache License Version 2.0 (the "License"). You may not use this file
# except in compliance with the License. You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0.
#
# This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. Refer to the License for the specific permissions and
# limitations governing your use of the file.
#

# Determine the location of the script to locate parcel
# Reference: http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
SOURCE="${BASH_SOURCE[0]}"
BIN_DIR="$(dirname "$SOURCE")"
while [ -h "$SOURCE" ]
do
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  BIN_DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done
BIN_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# Populate necessary environment variables
source $BIN_DIR/env.sh

if [ -f "kerberos.properties" ]; then
    generated_dir=generated
    mkdir -p "$generated_dir"
    keystore_file=flink_internal.jks
    keystore_name=$generated_dir/$keystore_file
    if [ ! -f "$keystore_name" ]; then

       ssl_properties=$generated_dir/internal_ssl.properties
       keystore_pass=$(openssl rand -base64 18)
       ${KEYTOOL_RUN} -genkeypair -alias flink.internal -keystore ${keystore_name} -dname "CN=flink.internal" -storepass ${keystore_pass} -keyalg RSA -keysize 4096 -storetype PKCS12
       printf 'flink.internal.keystore=%s\nflink.internal.password=%s\n' "${keystore_file}" "${keystore_pass}"  > ${ssl_properties}
       chmod 600 ${ssl_properties}
       chmod 600 ${keystore_name}
    fi
fi