#!/usr/bin/env bash

#
# Copyright 2020 - 2022 Cloudera. All Rights Reserved.
#
# This file is licensed under the Apache License Version 2.0 (the "License"). You may not use this file
# except in compliance with the License. You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0.
#
# This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. Refer to the License for the specific permissions and
# limitations governing your use of the file.
#

if [ -f "kerberos.properties" ]; then
    generated_dir=generated
    mkdir -p "$generated_dir"
    keystore_file=flink_internal.jks
    keystore_name=$generated_dir/$keystore_file
    if [ ! -f "$keystore_name" ]; then

       # Autodetect JAVA_HOME if not defined
       if [ -e /usr/bin/bigtop-detect-javahome ] ; then
           . /usr/bin/bigtop-detect-javahome
       fi

       if [[ -d "$JAVA_HOME" ]]; then
         KEYTOOL_RUN="$JAVA_HOME"/bin/keytool
       else
         KEYTOOL_RUN=keytool
       fi

       ssl_properties=$generated_dir/internal_ssl.properties
       keystore_pass=$(openssl rand -base64 18)
       ${KEYTOOL_RUN} -genkeypair -alias flink.internal -keystore ${keystore_name} -dname "CN=flink.internal" -storepass ${keystore_pass} -keyalg RSA -keysize 4096 -storetype PKCS12
       printf 'flink.internal.keystore=%s\nflink.internal.password=%s\n' "${keystore_file}" "${keystore_pass}"  > ${ssl_properties}
       chmod 600 ${ssl_properties}
       chmod 600 ${keystore_name}
    fi
fi