#!/usr/bin/env bash

#
# Copyright 2020 - 2022 Cloudera. All Rights Reserved.
#
# This file is licensed under the Apache License Version 2.0 (the "License"). You may not use this file
# except in compliance with the License. You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0.
#
# This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. Refer to the License for the specific permissions and
# limitations governing your use of the file.
#

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 jar_prefix" >&2
    exit 1
fi
jar_prefix=$1

## Build the jar path
#  current directory
jar_paths=(".")
# CYBERSEC_HOME/jobs if defined
if [[ ! -z "${CYBERSEC_HOME}" ]]; then
    jar_paths+=("${CYBERSEC_HOME}/jobs")
    jar_paths+=("${CYBERSEC_HOME}/tools")
fi
# parcel directory
jar_paths+=("/opt/cloudera/parcels/CYBERSEC/jobs")
jar_paths+=("/opt/cloudera/parcels/CYBERSEC/tools")
jar_paths+=("/opt/cloudera/parcels/FLINK/lib/flink/lib/")

for jar_path in "${jar_paths[@]}";
do
   if [[ -d "$jar_path" ]]; then
       found_jar=$(find "$jar_path" -maxdepth 1 -name ${jar_prefix}*)
       if [ ! -z "$found_jar" ]; then
           echo "$found_jar"
           break
       fi
   fi
done