#!/usr/bin/env bash

#
# Copyright 2020 - 2022 Cloudera. All Rights Reserved.
#
# This file is licensed under the Apache License Version 2.0 (the "License"). You may not use this file
# except in compliance with the License. You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0.
#
# This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. Refer to the License for the specific permissions and
# limitations governing your use of the file.
#

ship_configs=()
ship_config() {
  if [ -f "$1" ]; then
    echo "INFO: HBase Configuration: adding file $1"
    ship_configs+=("-y" "$1")
  fi
}

override_hbase() {
    ship_config "core-site.xml"
    ship_config "hdfs-site.xml"
    ship_config "hbase-site.xml"

    if [ "${#ship_configs[@]}" -eq 0 ]; then
        if [ -f "hbase-conf/hbase-site.xml" ]; then
            hbase_conf_dir="$(pwd)/hbase-conf"
            echo "INFO: HBase Configuration: using directory $hbase_conf_dir"
            export "HBASE_CONF_DIR=$hbase_conf_dir"
        else
            echo "INFO: HBase Configuration: using default"
        fi
    fi
}