#!/usr/bin/env bash

#
# Copyright 2020 - 2022 Cloudera. All Rights Reserved.
#
# This file is licensed under the Apache License Version 2.0 (the "License"). You may not use this file
# except in compliance with the License. You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0.
#
# This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. Refer to the License for the specific permissions and
# limitations governing your use of the file.
#
set -x

if [ "$#" -lt 2 ]; then
    echo "Usage: $0 jar_prefix class_name {options}" >&2
    exit 1
fi

jar_prefix=$1
class_name=$2
options=()

i=0;
for arg in "$@"
do
    if [ "$i" -gt 1 ]; then
        options+=("$arg")
    fi
    ((i+=1))
done


# Autodetect JAVA_HOME if not defined
if [ -e /usr/bin/bigtop-detect-javahome ] ; then
    . /usr/bin/bigtop-detect-javahome
fi

if [[ -d "$JAVA_HOME" ]]; then
    JAVA_RUN="$JAVA_HOME"/bin/java
else
    JAVA_RUN=java
fi


jar_path=$(cs-lookup-jar "$jar_prefix")
flink_dist=$(cs-lookup-jar "flink_dist")
log4j_config=$(cs-lookup-jar "log4j.properties")
lib_jars=$(ls -d -1 $CYBERSEC_HOME/lib/*.jar | tr '\n' ':' | sed 's/:$/\n/')
flink_dist=$(find /opt/cloudera/parcels/FLINK/ -name "flink-dist*.jar")

"$JAVA_RUN" -Dlog4j.configuration="$log4j_config" -Dlog4j.configurationFile="$log4j_config" -cp "$jar_path:$lib_jars:$flink_dist" $class_name "${options[@]}"
