#!/usr/bin/env bash

#
# Copyright 2020 - 2022 Cloudera. All Rights Reserved.
#
# This file is licensed under the Apache License Version 2.0 (the "License"). You may not use this file
# except in compliance with the License. You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0.
#
# This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. Refer to the License for the specific permissions and
# limitations governing your use of the file.
#

# Determine the location of the script to locate parcel
# Reference: http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
SOURCE="${BASH_SOURCE[0]}"
BIN_DIR="$(dirname "$SOURCE")"
while [ -h "$SOURCE" ]
do
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  BIN_DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done
BIN_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# Populate necessary environment variables
source $BIN_DIR/env.sh

if [ "$#" -ne 3 ]; then
  echo "Usage: $0 branch pipeline generator" >&2
  exit 1
fi

branch=$1
pipeline=$2
generator=$3

if [ ! -d "$pipeline" ]; then
    echo "pipeline $pipeline does not exist"
    exit 1
fi

if [ ! -f "$pipeline/generate/$generator/generator.properties.template" ]; then
    echo "pipeline $pipeline generator $generator does not exist"
    exit 1
fi

generated_dir=generated/$pipeline/generate/$generator
mkdir -p "$generated_dir"
generated_generator_props=$generated_dir/generator.properties
echo "# GENERATED FILE - EDITS WILL BE OVERWRITTEN - EDIT generator.properties.template instead." > $generated_generator_props
sed -e s/BRANCH/$branch/g $pipeline/generate/$generator/generator.properties.template >> $generated_generator_props
job_name=${branch}.${pipeline}.generate.${generator}

cs-cancel-job ${job_name}

cs-start-job -j caracal-generator -y $pipeline/generate/$generator/templates -p /etc/cybersec/conf/generator.properties -p kafka.properties -p "${generated_generator_props}"

