#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 job_name" >&2
  exit 1
fi

job_name=$1

job_id=$(flink list 2>&1 | grep "${job_name}" | awk '{print $4}')
job_status=$(flink list 2>&1 | grep "${job_name}" | awk '{print $7}')

if [ ! -z "$job_id" ]; then
   if [ "$job_status" = "(RUNNING)" ]; then
       flink stop $job_id 2>&1 |  grep "Savepoint completed" | awk '{print $4 }'
   else 
       flink cancel $job_id 2>&1 > /dev/null
   fi
fi
