#!/usr/bin/env bash

ssl_client_config="/etc/hadoop/conf/ssl-client.xml"
if [ -f /etc/hadoop/conf/ssl-client.xml ]; then
      truststore_location=$(cat "$ssl_client_config" | grep -A 1 ssl.client.truststore.location | grep value | awk -F'<|>' '{print $3}')
      truststore_password=$(cat /etc/hadoop/conf/ssl-client.xml | grep -A 1 ssl.client.truststore.password | grep value | awk -F'<|>' '{print $3}')
      echo "kafka.ssl.truststore.location=$truststore_location"
      echo "kafka.ssl.truststore.password=$truststore_password"
      echo "schema.registry.client.ssl.trustStorePath=$truststore_location"
      echo "schema.registry.client.ssl.trustStorePassword=$truststore_password"
else
   echo "ERROR: Could not find $ssl_client_config"
fi
