#!/usr/bin/env bash

#
# Copyright 2020 - 2022 Cloudera. All Rights Reserved.
#
# This file is licensed under the Apache License Version 2.0 (the "License"). You may not use this file
# except in compliance with the License. You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0.
#
# This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. Refer to the License for the specific permissions and
# limitations governing your use of the file.
#

ssl_client_config="/etc/hadoop/conf/ssl-client.xml"
if [ -f /etc/hadoop/conf/ssl-client.xml ]; then
      truststore_location=$(cat "$ssl_client_config" | grep -A 1 ssl.client.truststore.location | grep value | awk -F'<|>' '{print $3}')
      truststore_password=$(cat /etc/hadoop/conf/ssl-client.xml | grep -A 1 ssl.client.truststore.password | grep value | awk -F'<|>' '{print $3}')
      echo "kafka.ssl.truststore.location=$truststore_location"
      echo "kafka.ssl.truststore.password=$truststore_password"
      echo "schema.registry.client.ssl.trustStorePath=$truststore_location"
      echo "schema.registry.client.ssl.trustStorePassword=$truststore_password"
else
   echo "ERROR: Could not find $ssl_client_config"
fi
