#!/bin/sh

java -cp /opt/cloudera/CYBERSEC/tools/scoring-commands-${cybersec.full.version}.jar:/opt/cloudera/CYBERSEC/lib/slf4j-api-${slf4j.version}.jar  com.cloudera.cyber.scoring.UpsertScoringRule /opt/cloudera/CYBERSEC/etc/conf/scoring.properties /opt/cloudera/CYBERSEC/tools/sample-rule.json
