#!/bin/bash

YARN_JOB_MANAGER_MEMORY="1024"
YARN_TASK_MANAGER_MEMORY="1024"
YARN_NAME="yarn.generator.job"
PROPERTIES_FILE=$(pwd)/generator.properties

usage="$(basename "$0") [-h] [-s n] -- program to calculate the answer to life, the universe and everything

where:
    -j  show this help text
    -t  set the seed value (default: 42)
    -n  Yarn job name
    -p  Path to properties file
    "


while getopts "j:t:n:p:h" option; do
  case $option in
    j) YARN_JOB_MANAGER_MEMORY="$OPTARG"
    ;;
    t) YARN_TASK_MANAGER_MEMORY="$OPTARG"
    ;;
    n) YARN_NAME="$OPTARG"
    ;;
    p) PROPERTIES_FILE="$OPTARG"
    ;;
    h) echo $usage
       exit 0
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    exit 1
    ;;
  esac

  case $OPTARG in
    -*) echo "Option $option needs a valid argument"
    exit 1
    ;;
  esac
done

flink run --jobmanager yarn-cluster -yjm $YARN_JOB_MANAGER_MEMORY -ytm $YARN_TASK_MANAGER_MEMORY  --detached --yarnname $YARN_NAME \
      /opt/cloudera/parcels/CYBERSEC/jobs/caracal-generator-${cybersec.full.version}.jar /etc/cybersec/conf/kafka.properties /etc/cybersec/conf/generator.properties $PROPERTIES_FILE
