#!/usr/bin/env bash

#
# Copyright 2020 - 2022 Cloudera. All Rights Reserved.
#
# This file is licensed under the Apache License Version 2.0 (the "License"). You may not use this file
# except in compliance with the License. You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0.
#
# This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. Refer to the License for the specific permissions and
# limitations governing your use of the file.
#

export HADOOP_CLASSPATH=`hadoop classpath`

YARN_JOB_MANAGER_MEMORY="1024"
YARN_TASK_MANAGER_MEMORY="1024"
YARN_NAME="yarn.hive.indexing.job"
PROPERTIES_FILE=$(pwd)/profile.properties

usage="$(basename "$0") [-h] [-s n] -- program to calculate the answer to life, the universe and everything

where:
    -j  show this help text
    -t  set the seed value (default: 42)
    -y  CONFIG_DIR path
    -n  Yarn job name
    -p  Path to properties file
    -s save point
    "


while getopts "j:t:n:p:h" option; do
  case $option in
    j) YARN_JOB_MANAGER_MEMORY="$OPTARG"
    ;;
    t) YARN_TASK_MANAGER_MEMORY="$OPTARG"
    ;;
    n) YARN_NAME="$OPTARG"
    ;;
    p) PROPERTIES_FILE="$OPTARG"
    ;;
    h) echo "$usage"
       exit 0
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    exit 1
    ;;
  esac

  case $OPTARG in
    -*) echo "Option $option needs a valid argument"
    exit 1
    ;;
  esac
done

flink run \
--classpath file:///etc/hive/conf/hive-site.xml \
--classpath file:///etc/hadoop/conf/core-site.xml \
--jobmanager yarn-cluster -yjm $YARN_JOB_MANAGER_MEMORY -ytm $YARN_TASK_MANAGER_MEMORY--detached --yarnname $YARN_NAME \
 opt/cloudera/parcels/CYBERSEC/jobs/flink-indexing-hive-${cybersec.full.version}.jar /etc/cybersec/conf/kafka.properties /etc/cybersec/conf/hive-indexing.properties $PROPERTIES_FILE