#!/bin/bash

YARN_JOB_MANAGER_MEMORY="2048"
YARN_TASK_MANAGER_MEMORY="2048"
YARN_NAME="yarn.triage.job"
PROPERTIES_FILE=$(pwd)/triage.properties
savepoint=

usage="$(basename "$0") [-h] [-s n] -- program to calculate the answer to life, the universe and everything

where:
    -j  show this help text
    -t  set the seed value (default: 42)
    -y  CONFIG_DIR path
    -n  Yarn job name
    -p  Path to properties file
    -s save point
    "


while getopts "j:t:n:p:s:h" option; do
  case $option in
    j) YARN_JOB_MANAGER_MEMORY="$OPTARG"
    ;;
    t) YARN_TASK_MANAGER_MEMORY="$OPTARG"
    ;;
    n) YARN_NAME="$OPTARG"
    ;;
    p) PROPERTIES_FILE="$OPTARG"
    ;;
    s) savepoint="-s $OPTARG"
    ;;
    h) echo $usage
       exit 0
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    exit 1
    ;;
  esac

  case $OPTARG in
    -*) echo "Option $option needs a valid argument"
    exit 1
    ;;
  esac
done

flink run -yt /etc/hadoop/conf/core-site.xml  -yt /etc/hbase/conf/hbase-site.xml $savepoint \
 --jobmanager yarn-cluster -yjm $YARN_JOB_MANAGER_MEMORY -ytm $YARN_TASK_MANAGER_MEMORY  --detached --yarnname $YARN_NAME \
 /opt/cloudera/parcels/CYBERSEC/jobs/flink-enrichment-combined-${cybersec.full.version}.jar /etc/cybersec/conf/kafka.properties /opt/cloudera/parcels/CYBERSEC/etc/conf/triage.properties $PROPERTIES_FILE
