#!/bin/sh

flink run --jobmanager yarn-cluster -yjm 1024 -ytm 1024 -yt netflow.schema --detached --yarnname "Parser" \
    /opt/cloudera/CYBERSEC/jobs/parser-chains-flink-${cybersec.full.version}.jar /opt/cloudera/CYBERSEC/etc/conf/6parser.properties
