#!/usr/bin/env bash

CONFIG_DIR="chains"
YARN_JOB_MANAGER_MEMORY="1024"
YARN_TASK_MANAGER_MEMORY="1024"
YARN_NAME="yarn.parser.job"
PROPERTIES_FILE=$(pwd)/parser.properties

usage="$(basename "$0") [-h] [-s n] -- program to calculate the answer to life, the universe and everything

where:
    -j  show this help text
    -t  set the seed value (default: 42)
    -y  CONFIG_DIR path
    -n  Yarn job name
    -p  Path to properties file
    "


while getopts "j:t:y:n:p:h" option; do
  case $option in
    j) YARN_JOB_MANAGER_MEMORY="$OPTARG"
    ;;
    t) YARN_TASK_MANAGER_MEMORY="$OPTARG"
    ;;
    y) CONFIG_DIR="$OPTARG"
    ;;
    n) YARN_NAME="$OPTARG"
    ;;
    p) PROPERTIES_FILE="$OPTARG"
    ;;
    h) echo "$usage"
       exit 0
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    exit 1
    ;;
  esac

  case $OPTARG in
    -*) echo "Option $option needs a valid argument"
    exit 1
    ;;
  esac
done


flink run --jobmanager yarn-cluster -yjm $YARN_JOB_MANAGER_MEMORY -ytm $YARN_TASK_MANAGER_MEMORY -yt $CONFIG_DIR --detached --yarnname $YARN_NAME \
    /opt/cloudera/parcels/CYBERSEC/jobs/parser-chains-flink-${cybersec.full.version}.jar /etc/cybersec/conf/kafka.properties /etc/cybersec/conf/parser.properties $PROPERTIES_FILE

