#!/usr/bin/env bash

PHOENIX_CLIENT_JAR=$(ls /opt/cloudera/parcels/CDH/lib/phoenix_queryserver/phoenix-queryserver-client-*.jar -1)

YARN_JOB_MANAGER_MEMORY="2048"
YARN_TASK_MANAGER_MEMORY="2048"
YARN_NAME="yarn.profile.job"
PROPERTIES_FILE=$(pwd)/profile.properties

usage="$(basename "$0") [-h] [-s n] -- program to calculate the answer to life, the universe and everything

where:
    -j  show this help text
    -t  set the seed value (default: 42)
    -y  CONFIG_DIR path
    -n  Yarn job name
    -p  Path to properties file
    -s save point
    "


while getopts "j:t:n:p:h" option; do
  case $option in
    j) YARN_JOB_MANAGER_MEMORY="$OPTARG"
    ;;
    t) YARN_TASK_MANAGER_MEMORY="$OPTARG"
    ;;
    n) YARN_NAME="$OPTARG"
    ;;
    p) PROPERTIES_FILE="$OPTARG"
    ;;
    h) echo "$usage"
       exit 0
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    exit 1
    ;;
  esac

  case $OPTARG in
    -*) echo "Option $option needs a valid argument"
    exit 1
    ;;
  esac
done

flink run --jobmanager yarn-cluster  -yjm $YARN_JOB_MANAGER_MEMORY -ytm $YARN_TASK_MANAGER_MEMORY  \
 --classpath file://${PHOENIX_CLIENT_JAR} \
 --detached --yarnname $YARN_NAME /opt/cloudera/parcels/CYBERSEC/jobs/flink-profiler-java-${cybersec.full.version}.jar /etc/cybersec/conf/kafka.properties /opt/cloudera/parcels/CYBERSEC/etc/conf/profile.properties $PROPERTIES_FILE
