CREATE TABLE IF NOT EXISTS ${profile_metadata_table_name} (
    ID BIGINT PRIMARY KEY,
    PROFILE_GROUP_NAME VARCHAR,
    KEY_FIELD_NAMES VARCHAR,
    PERIOD_DURATION BIGINT,
    PERIOD_DURATION_UNIT VARCHAR,
    STATS_SLIDE BIGINT,
    STATS_SLIDE_UNIT VARCHAR
)