# Main configuration entry point for the application

server:
  servlet:
    context-path: /
  tomcat:
    accesslog:
      enabled: true

# Enable/disable and expose/hide web enpoints for Actuator admin services
management.endpoints.web:
  exposure.include: info, health

# main application logging
logging:
  level:
    root: WARN
    org:
      apache:
        tomcat: INFO
        catalina: INFO

security:
  kerberos:
    enabled: false
    serviceName: cm_cybersec
    appId: cm_cybersec
    spnego:
      keytab: cybersec.keytab

# Swagger
springdoc:
  api-doc:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui


# Kafka
spring:
  kafka:
    bootstrap-servers: localhost:9092
    reply-topic: reply-topic
    request-topic: request-topic
    consumer:
      group-id: my-consumer-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    external-clusters:
      clusterId1:
        bootstrap-servers: localhost:9092
        reply-topic: reply-topic
        request-topic: request-topic
        consumer:
          group-id: my-consumer-group
          auto-offset-reset: latest
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.apache.kafka.common.serialization.StringSerializer
